### ISSUE TITLE
PRODUÇÕES CIENTÍFICAS

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/elmo#104]
Registro de trabalhos escritos ou sugestões de temáticas futuras

Trabalhos já submetidos:
- "Treinamento Elmo e o Uso de Métodos Ágeis no Setor Público"
https://docs.google.com/document/d/1UYw4S7Hk7JVLlarhjS70EVtYUgP0ow3n/edit

**Comment by marameida** [comment]
Registro de sugestões futuras até o momento:
- Categorização de respostas provindas do freshdesk;
- Utilização da Política Pública de Inovação na construção do PPA;

**Comment by geniltonfaheinajr** [comment]
Samara, registra aqui a ultima versão que enviamos. A versão em word.

**Comment by clarissagpeixoto** [comment]
Artigo para discussão posterior sobre a Lei de Licitações e Contratos (Lei n.º 8.666/1993) e a Lei de Inovação Tecnológica (Lei n.º 10.973/2004): 

https://jus.com.br/artigos/35466/os-entraves-da-lei-de-inovacao-tecnologica-quanto-as-contratacoes-publicas-para-transferencia-de-tecnologia

**Comment by clarissagpeixoto** [comment]
Arquivo final, com exclusão dos agradecimentos aqui: https://docs.google.com/document/u/1/d/1OEwt1Tp4aRPK_8NUhsmV5LeT5k5PEb-M/edit?usp=drive_web&ouid=104430130345191947090&rtpof=true
