### ISSUE TITLE
Melhorar a visualização do termo "ELMO" em sites de busca

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/elmo#13]
Percebo que temos um problema com relação às questões de Search Engine Optimization (SEO)
As páginas (site) do ELMO, por estarem em um sub diretório do domínio https://sus.ce.gov.br / https://sus.ce.gov.br/elmo/
O sistemas de buscas, também conhecidos como "aranhas" realizam sua buscas em primeiro lugar na página inicial de um domínio, no nosso caso (https://sus.ce.gov.br) a partir da indexação dos conteúfos
encontrados, os bots (também assim chamados) irão fazer uma "varredura" no restante do site. Como nossa página inicial do domínio não foi trabalhada levando em consideração estes fatores, o site do ELMO,
consequentemente não aparecerá nos resultados de buscas nos sites que se propõem a realizar esta tarefa.

Sistema de buscas no site da ESP:
* Pesquisar por ELMO não retorna nenhum resultado
* As postagens sobre o ELMO não possuem nenhum link para a página
Hoje:
https://coronavirus.ceara.gov.br/ (não abre)

Devemos e precisamos usar todos os recursos disponíveis para ter visibilidade
https://developers.google.com/search/docs/beginner/get-started
https://search.google.com/search-console/about

Mais detalhes:
https://trello.com/c/ahzKdwpZ

**Comment by marameida** [comment]
Reunião semanal com Daniel/Washington do designlab

**Comment by marameida** [comment]
- 05/05/2021: Refinamento com daniel DesignLab;
- Necessidade de envolvimento com Publicilab, ASCOM e Superintendencia;
-

**Comment by RaniGub** [comment]
Foram realizados testes e o contexto da tarefa não condiz com o retorno de busca dos sistema. Samara moveu para concluída em seu Board. Tarefa finalizada pelo DesignLab.
