### ISSUE TITLE
Mapear devolutivas das propostas enviadas- GERAR RELATÓRIOS CRM

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/elmo#44]
## **Objetivo**

**Como** usuário do CRM 
**Quero** mapear devolutivas das propostas enviadas
**Para** compreender melhor o padrão de retorno dos tomadores de serviços.

## **Contexto**
A maioria dos emails enviados com as propostas, não estão sendo respondidos pelos tomadores de serviços.

## **Escopo**

- [ x ] Criar planilha de mapeamento;
- [   ] Discutir com designlab como esses relatórios podem ser gerados de forma automatizada pelo CRM;

## **Fora de Escopo**
- Não queremos desconhecer os reais motivos da falta de resposta do tomador de serviço ao envio de propostas.

## **Critérios de Aceitação**

**Dado que**com o mapeamento 
**Quando** acessarmos o relatório gerado pelo CRM
**então** conheceremos melhor os motivos e padrão de devolutiva das respostas às propostas de treinamento.

# Observações

Planilha pré-elaborada:
https://docs.google.com/spreadsheets/d/1Wi3rEisbSWFdGQrnh9Gl2UyVOxVex-Yq/edit#gid=441532153

**Comment by marameida** [comment]
Analisar a possibilidade de incluir uma nova aba para facilitar visualização de respostas pelos tomadores de serviço.

**Comment by marameida** [comment]
Atualizar fluxo - Inclusão de aba "À PROTOCOLAR"

**Comment by wforte88** [comment]
Criada nova coluna "A protocolar" para indicar os negócios que aceitaram a proposta e estão em fase de coleta de dados adicionais para protocolar o processo e iniciar a contratação.

Os motivos de desistência serão informados ao mover um negócio (card) para a coluna "Desistente", dessa forma o CRM já tratará esse dado nos relatórios.
