### ISSUE TITLE
Atualizar número de pessoas treinadas no site.

### ISSUE THREAD

**Issue by clarissagpeixoto** [EscolaDeSaudePublica/elmo#60]
## **Objetivo**
Atualizar número de pessoas treinadas pela ESP semanalmente
**Como** usuária do site Elmo
**Quero** visualizar o número atualizado de pessoas treinadas semanalmente
**Para** dar visibilidade ao trabalho desenvolvido pela ESP.

## **Contexto**
O número de pessoas treinadas precisa ser visualizado semanalmente de forma atualizada na página inicial.

 ## **Escopo**

- [x] Repassar semanalmente para Designlab o número atualizado de pessoas treinadas via telegram ou reunião semanal de equipe.

## **Critérios de Aceitação**

**Dado que** feito acesso do site do Elmo
**Quando** rola a página inicial
**então** vejo a visualização do resultado .dos treinamentos

**Comment by clarissagpeixoto** [comment]
@danielgula favor atualizar número de pessoas treinadas no site do Elmo. Dado passado hoje, dia 25/05/2021, pela Cléo, do CEDES, por e-mail: 1.032

**Comment by clarissagpeixoto** [comment]
@marameida Dado passado hoje, dia 25/05/2021, pela Cléo, do CEDES, por e-mail: 1.032 pessoas treinadas.

**Comment by marameida** [comment]
Será repassado para @danielgula em reunião semanal (27/05) às 14h

**Comment by marameida** [comment]
Repassar semanalmente para Designlab (@danielgula ) o número atualizado de pessoas treinadas via telegram e email, dado informado pelo CEDES à equipe Elmo.

**Comment by clarissagpeixoto** [comment]
@marameida pq está como concluída essa tarefa se ela é recorrente?
