### ISSUE TITLE
Criar novo espaço "ESPvirtual" no app iSUS sessão Elmo

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/elmo#72]
## **Objetivo**

**Como** usuário do app iSUS
**Quero** visualizar o item "ESPvirtual" 
**Para** estar melhor integrada ao "ambiente virtual de aprendizagem" .

## **Contexto**
Atualmente quando acessamos a área do Elmo, visualizamos três ícones: "capacitação"; "manual de uso"; "fale conosco". Necessita-se incluir item "ESPvirtual", fazendo link o AVA

## **Escopo**

- [ ] Incluir item "ESPvirtual" na sessão Elmo do app iSUS;
- [ ] Integrar as informações presentes no site Elmo com o AVA;

## **Critérios de Aceitação**

**Dado que**ao acessar a área do Elmo
**Quando**  no item "ESPvirtual" do app iSUS
**então** podemos  visualizar o AVA e consequentes espaços dos cursos do Elmo.

# Observações
https://www.esp.ce.gov.br/2019/01/14/esp-virtual/

**Comment by marameida** [comment]
Agendada reunião de refinamento com @danielgula, Clayton e @chicaothiago
Data: 09/06/2021
Horário: 9h

**Comment by marameida** [comment]
Ata breve de reunião 09/06/21: presentes Samara, Clayton, Cleo, Chicão e Daniel.

- Discutido como fazer melhor integração entre AVA e site ELMO;
- Espaço para acesso ao AVA descrito na aba "TREINAMENTOS" e no MENU de opções do site.
- Necessário maior detalhamento sobre os tipos de treinamento (EAD e PRESENCIAL no site), informando sobre as demais ferramentas (iSUS e AVA) que fazem parte do suporte pós-treinamento.

SUGESTÕES DE ENCAMINHAMENTO:
- Produção de novos vídeos detalhando o acesso e os tipos de ferramentas de suporte;
- Inclusão de mais depoimentos no site, sendo coletados com profissionais que fizeram o treinamento.

**Comment by marameida** [comment]
Aguardando retorno com @chicaotgv .

**Comment by marameida** [comment]
Ainda no aguardo por ajustes no aplicativo ISUS. Confirmado com @oxechicao. Última informação: problemas para por em produção, pois estão tentando lançar nova versão.

**Comment by marameida** [comment]
Ações implementadas, porém no aguardo por nova versão devido pendência de aceitação pela Apple.

**Comment by marameida** [comment]
No aguardo por validação da Apple para lançamento da nova versão do aplicativo.

**Comment by marameida** [comment]
Atividade ainda em aberto. Incluir URL e solicitar imagem atualizada com Designlab. Já repassado para @oxechicao.

http://cursos.espvirtual.esp.ce.gov.br/

**Comment by marameida** [comment]
Especificação de imagem à ser incluída:

largura="140"
altura="100"

No formato SVG

Atualmente são como se fossem ícones:
Possuem as cores

plano de fundo: #2DAFE6
icone: #fff

Necessário adaptação de imagem do local "espvirtual" presente na página principal do aplicativo com fundo amarelo para fundo azul a ser incluída na página "Elmo" do iSUS. (@danielgula )

**Comment by danielgula** [comment]
Botão criado e enviado a @marameida e @oxechicao

**Comment by marameida** [comment]
Ciente. Obrigada. No aguardo por ajuste no aplicativo.

**Comment by marameida** [comment]
Imagem recebida. 
file:///C:/Users/samar/Downloads/icon-elmo-espvirtual.svg

Foi reforçado com @oxechicao para ser incluída no aplicativo.

**Comment by clarissagpeixoto** [comment]
Finalizando a tarefa, pois a sessão encontra-se criada. Print da tela anexo:
![WhatsApp Image 2021-09-24 at 11 56 02](https://user-images.githubusercontent.com/77675469/134696929-334f80fc-5f4c-40cb-a326-4531eb096c38.jpeg)

**Comment by danielgula** [comment]
@marameida @marameida @janeteamaral essa demanda está encerrada? Encontrei aqui no board do sus.ce como concluída e estou atualizando as tarefas.
