### ISSUE TITLE
Automatizar envio de mensagens do CEDES.

### ISSUE THREAD

**Issue by clarissagpeixoto** [EscolaDeSaudePublica/elmo#91]
## **Objetivo**

**Como**  participante do projeto Elmo
**Quero** incluir uma mensagem automático quando pedido de treinamento pelo site
**Para** informar ao usuário que o processo dele está em andamento.

## **Contexto**
Quando é feito o cadastro no site do Elmo, as pessoas da iniciativa privada recebem um e-mail de confirmação de recebimento. O pessoal do serviço público não recebe comunicação alguma. 

## **Escopo**

- [] Automatizar o envio de mensagem também para o pessoal do SUS.

## **Fora de Escopo**

A mensagem é a seguinte:

Olá, XXXXXXXXXXX ,

Confirmamos o recebimento da sua solicitação de treinamento para uso do Elmo. Diante do cenário que estamos enfrentando, a Escola de Saúde Pública do Ceará (ESP/CE) não possui capacidade de pronto atendimento. Por conta disso, a sua solicitação foi incluída em uma lista de espera.

 **Tão logo seja possível, entraremos em contato por e-mail ou telefone. Fique atenta (o)!**

 Enquanto isso, descubra mais sobre o Elmo na nossa página aberta de materiais instrucionais.

Abraço virtual,

Equipe Elmo
Escola de Saúde Pública do Ceará
sus.ce.gov.br/elmo

**Comment by clarissagpeixoto** [comment]
Mensagens futuras que poderão ser automatizadas (a pedido do CEDES) já criadas:

Olá, Fulano ,

Recebemos sua solicitação de treinamento para uso do Elmo. Entretanto, por enquanto, devido a nossa capacidade de atendimento, estamos capacitando apenas médicos, enfermeiros, fisioterapeutas e engenheiros clínicos.
Nossa equipe está trabalhando para que sua categoria possa participar dos treinamentos. Sabemos da importância em incluí-la. Assim que tivermos novidades, entraremos em contato. 
Enquanto isso, descubra mais sobre o Elmo na nossa página aberta de materiais instrucionais.

Abraço virtual,

Equipe Elmo
Escola de Saúde Pública do Ceará
sus.ce.gov.br/elmo
________________________________________
Olá, Fulano ,

Somos do projeto Elmo, da Escola de Saúde Pública do Ceará. Estamos passando para informar que, devido a sua ausência sem justificativa no último treinamento para uso do capacete Elmo, infelizmente, você está sendo transferido para uma lista de desistentes. Caso ainda haja interesse no treinamento, por favor, entre em contato conosco.

Abraço virtual,

Equipe Elmo
Escola de Saúde Pública do Ceará
sus.ce.gov.br/elmo

**Comment by marameida** [comment]
Ciente. Será repassado ao designlab para solicitação de automação.

**Comment by marameida** [comment]
No aguardo por retorno do designlab.

**Comment by clarissagpeixoto** [comment]
A discussão vai ser feita manhã, às 9h, com o DesignLab.

**Comment by marameida** [comment]
Acordado que @danielgula juntamente com a equipe fará este ajuste.

**Comment by marameida** [comment]
Reforçado com @danielgula essa demanda.

**Comment by clarissagpeixoto** [comment]
@danielgula conseguiu ver alguma coisa em relação a essa semana?

**Comment by danielgula** [comment]
> @danielgula conseguiu ver alguma coisa em relação a essa semana?

Está na esteira de priorização do Designlab.

**Comment by danielgula** [comment]
@clarissagpeixoto conforme apoio dado a essa demanda, podemos concluir?

**Comment by clarissagpeixoto** [comment]
@danielgula sim, tarefa concluída.
